# Generated by Django 2.2.1 on 2019-06-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190625_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(blank=True, default='message', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='phone',
            field=models.CharField(default='phone', max_length=100),
        ),
    ]
